# Default values for console-banner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Production values
clusterName: gitops
backgroundColor: '#12890e' # green
textColor: '#FFFFFF' # white
location: BannerTop
