# Default values for fio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#FIO Configuration
fio:
  name: file-integrity-operator
  namespace: openshift-file-integrity
  config:
    enable: false
    name: "ChangeMe"
    key: "ChangeMe"
    gracePeriod: 20
    maxBackups: 5
    initialDelay: 60
  debug: false
  custom_tolerations: false
